# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 晴风的博客
subtitle: 晴风
description:
keywords: "···计算机,软工,Android,iOS,macOS,Linux,C,C++,Java,Python,Objective-C,Swift···"
author: XQ
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.xq99.org/
# url: https://blog.4live.host
root: /
permalink: /posts/:title/ ##:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - CNAME
  - README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: true
post_asset_folder: true ########
relative_link: false #出现跳转一个页面
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false #######
  tab_replace:


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Extensions 扩展
## Plugins: https://hexo.io/plugins/ #插件
plugins:
  hexo-generator-feed #RSS订阅插件
  #hexo-generator-baidu-sitemap  #sitemap插件
  #hexo-generator-sitemap

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: mynext
theme: archer


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    # github: git@github.com:xq773939719/matery.git,master
    # gitee: git@gitee.com:xq773939719/xq773939719.git,master
    # bitbucket: git@bitbucket.org:xq773939719/xq773939719.bitbucket.io.git,master

    coding: git@e.coding.net:xq773939719/xq773939719.coding.me/Blog.git,master
    # gitlab: git@gitlab.com:xq773939719/xq773939719.gitlab.io.git,master


  branch: master

#自定义
avatar: /images/avatar.jpg
duoshuo_shortname: XQ


archive_generator:
  per_page: 9
  yearly: true
  monthly: true

tag_generator:
  per_page: 12

# Archives
2: 开启分页
1: 禁用分页
0: 全部禁用
archive: 2
category: 2
tag: 2

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

leancloud_counter_security:
  enable_sync: true
  app_id: YWoGmJBtL0H01NObzadIB8dd-gzGzoHsz #<app_id>
  app_key: NhB5UIfHaVr6nBpuiRAz3t1E #<app_key>
  username:  xq773939719 # Will be asked while deploying if is left blank
  password:   # Recommmended to be left blank. Will be asked while deploying if is left blank


# hexo sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true


#添加图标<i class="fa fa-pencil"></i>支持Markdown

prism_plugin:
  mode: preprocess    # realtime/preprocess
  theme: tomorrow
  line_number: false    # default false
  custom_css:


########
#http://www.cnblogs.com/liziczh/p/9318656.html
#https://blog.csdn.net/kunkun5love/article/details/79130956
#https://www.jianshu.com/p/d23d67d318c7
#https://blog.csdn.net/heqiangflytosky/article/details/54863166
#https://blog.csdn.net/u010053344/article/details/50706790

jsonContent:
  meta: true
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true