
<!--<script type="text/javascript" src="/lib/clipboard/clipboard.min.js"></script>
<script type="text/javascript" src="/js/src/custom.js"></script>-->
<!-- 页面点击小红心 -->
<script type="text/javascript" src="/js/src/love.js"></script>


<!-- https://www.jianshu.com/p/3e9d614c1e77 -->
<!-- 代码块复制功能 -->
<script type="text/javascript" src="/js/src/clipboard.min.js"></script>  
<script type="text/javascript" src="/js/src/clipboard-use.js"></script>
